import { AboutNav } from "@/components";
import "../globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-indigo-200">
        <main className="flex  items-center justify-center p-24">
          <div className="items-center justify-center font-mono">
            <AboutNav />
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
